export const profiles = [
  {
    category: 'Développement web',
    keywords: [
      ['Directeur de la technologie', 'CTO'],
      ['R&D'],
      ['Architecte'],
      ['Administrateur de base de données'],
      ["Technologies de l'information"],
      ['Responsable informatique', 'IT Manager'],
      ['Spécialiste informatique', 'IT Specialist'],
      ['Administrateur informatique', 'IT Administrator'],
      ['Ingénieur logiciel', 'Software Engineer'],
      ['Programmeur'],
      ['Développeur'],
      ['Codeur'],
      ['Backend'],
      ['Frontend'],
      ['Back-end'],
      ['Front-end'],
      ['Développeur web'],
      ['Ingénieur web'],
      ['SEO'],
      ['Python'],
      ['Django'],
      ['Ruby'],
      ['Rails'],
      ['PHP'],
      ['JavaScript'],
      ['React'],
      ['ReactJS'],
      ['Angular'],
      ['AngularJS'],
      ['JS'],
      ['Java'],
      ['HTML'],
      ['CSS'],
      ['C#'],
      ['C++'],
      ['SQL'],
      ['MySQL'],
      ['Assurance qualité', 'QA'],
    ],
  },
  {
    category: 'Développement mobile',
    keywords: [
      ['Directeur de la technologie', 'CTO'],
      ['R&D'],
      ['Architecte'],
      ['Ingénieur mobile'],
      ['Ingénieur logiciel', 'Software Engineer'],
      ["Technologies de l'information"],
      ['Responsable informatique', 'IT Manager'],
      ['Spécialiste informatique', 'IT Specialist'],
      ['Administrateur informatique', 'IT Administrator'],
      ['Programmeur'],
      ['Développeur'],
      ['Codeur'],
      ['Objective-C'],
      ['Swift'],
      ['Java'],
      ['iOS'],
      ['Android'],
      ['Cordova'],
      ['Phonegap'],
      ['React Native'],
      ['Ionic'],
      ['Xcode'],
      ['Assurance qualité', 'QA'],
      ['Webmaster'],
    ],
  },
  {
    category: 'Data Science',
    keywords: [
      ['Directeur de la technologie', 'CTO'],
      ['Science des données', 'Data Science'],
      ['Data Scientist'],
      ['Apprentissage automatique', 'Machine Learning'],
      ['Apprentissage profond', 'Deep Learning'],
      ['Analytique'],
      ['Analyste'],
      ['Algèbre'],
      ['Théorie des probabilités', 'Probability Theory'],
      ['Statistiques'],
      ['Mathématiques'],
      ['Mathématicien'],
      ['Kaggle'],
      ['Spark'],
      ['Singa'],
      ['Hadoop'],
      ['Tensorflow'],
      ['Theano'],
      ['Torch'],
      ['Caffe'],
      ['CNTK'],
      ['MLlib'],
      ['Keras'],
      ['MXNet'],
      ['scikit'],
      ['Azure ML'],
      ['ML Studio'],
      ['R&D'],
    ],
  },
  {
    category: 'Design',
    keywords: [
      ['Design'],
      ['Designer'],
      ['Directeur créatif', 'Creative Director'],
      ['Responsable créatif', 'Creative Head'],
      ['Chef de projet créatif', 'Creative Lead'],
      ['Directeur artistique', 'Art Director'],
      ['UI'],
      ['UX'],
      ['Responsable artistique', 'Art Manager'],
      ['Identité de marque', 'Brand Identity'],
      ['Logo'],
      ['Illustrateur'],
      ['Illustration'],
      ['Artiste'],
      ['Graphiste'],
      ['Interface utilisateur', 'User Interface'],
      ['Expérience utilisateur', 'User Experience'],
      ['Prototypage'],
      ['Prototype'],
      ['Photoshop'],
      ['Sketch'],
      ['InDesign'],
      ['Adobe'],
    ],
  },
  {
    category: 'Relations publiques',
    keywords: [
      ['CEO'],
      ['Chief Executive Officer'],
      ['Communications'],
      ['Marketing'],
      ['Brand'],
      ['Branding'],
      ['Content', 'Manager'],
      ['Content', 'Strategist'],
      ['Copy', 'Writer'],
      ['Public', 'Affairs'],
      ['Public', 'Relations'],
      ['Event', 'Coordinator'],
      ['Event', 'Manager'],
      ['Social', 'Media'],
      ['Media', 'Director'],
      ['Media', 'Coordinator'],
      ['Relationship', 'Manager'],
      ['Media', 'Relations'],
      ['Media', 'Coordinator'],
      ['Media', 'Director'],
      ['Media', 'Specialist'],
    ],
  },
  {
    category: 'Marketing',
    keywords: [
      ['CEO'],
      ['Chief Executive Officer'],
      ['Marketing'],
      ['Marketer'],
      ['Account', 'Coordinator'],
      ['Account', 'Executive'],
      ['Advertising'],
      ['Ads'],
      ['Advert'],
      ['Art', 'Director'],
      ['Assistant', 'Director'],
      ['Brand'],
      ['Branding'],
      ['Product', 'Manager'],
      ['Business', 'Development'],
      ['Communications'],
      ['Content', 'Manager'],
      ['Content', 'Writer'],
      ['Community', 'Manager'],
      ['Copywriter'],
      ['Creative', 'Assistant'],
      ['Creative', 'Director'],
      ['Market', 'Research'],
      ['Media', 'Assistant'],
      ['Media', 'Buyer'],
      ['Media', 'Director'],
      ['Media', 'Planner'],
      ['Media', 'Researcher'],
      ['Media', 'Relations'],
      ['Promotion'],
      ['Promotions'],
      ['Public', 'Relations'],
      ['Publicity'],
      ['SEO'],
      ['Ecommerce'],
      ['E commerce'],
      ['PMM'],
    ],
  },
  {
    category: 'Human Resources',
    keywords: [
      ['HR'],
      ['Human Resources'],
      ['Talent'],
      ['Recruiter'],
      ['Recruiting'],
      ['Administrative'],
      ['Employee', 'Relations'],
      ['HRD'],
      ['Sourcing'],
      ['Staffing'],
    ],
  },
  {
    category: 'Sales & Business Development',
    keywords: [
      ['CEO'],
      ['Chief Executive Officer'],
      ['Sales'],
      ['Salesperson'],
      ['Salesman'],
      ['Dealer'],
      ['Business', 'Development'],
      ['Business', 'Manager'],
      ['Market', 'Development'],
      ['Account', 'Manager'],
      ['Account', 'Director'],
      ['Account', 'Representative'],
      ['Client', 'Relationship'],
      ['Customer', 'Relationship'],
      ['Customer', 'Success'],
      ['Customer', 'Care'],
      ['Telesales'],
      ['Brand', 'Ambassador'],
      ['Industry', 'Representative'],
      ['Retail'],
    ],
  },
  {
    category: 'Finance & Accounting',
    keywords: [
      ['Accounting'],
      ['Accountant'],
      ['Financial'],
      ['Finance'],
      ['Auditor'],
      ['Audit'],
      ['Bookkeeper'],
      ['Budget'],
      ['Payroll'],
      ['Tax'],
    ],
  },
  {
    category: 'Product Management',
    keywords: [
      ['Project', 'Management'],
      ['Product', 'Management'],
      ['Project', 'Manager'],
      ['Product', 'Manager'],
      ['Team', 'Lead'],
      ['Scrum'],
      ['Kanban'],
      ['PM'],
      ['PMM'],
      ['CEO'],
      ['CTO'],
      ['Chief Executive Officer'],
      ['Chief Technology Officer'],
      ['R&D'],
    ],
  },
  {
    category: 'Startups',
    keywords: [],
  },
];
